###
POST http://localhost:3001/card HTTP/1.1
Content-Type: application/json

  {
    "name": "bulbasaur",
    "hp": 45,
    "attack": 49,
    "defense": 49,
    "special_attack": 65,
    "special_defense": 65,
    "speed": 45
  }

###
GET http://localhost:3001/cards HTTP/1.1

###
GET http://localhost:3001/card HTTP/1.1
Content-Type: application/json

  {
    "id_card":2
  }

###
PUT http://localhost:3001/card HTTP/1.1
Content-Type: application/json

  {
    "name": "picachu",
    "hp": 45,
    "attack": 49,
    "defense": 49,
    "special_attack": 65,
    "special_defense": 65,
    "speed": 50,
    "id_card":2
  }

###
DELETE http://localhost:3001/card HTTP/1.1
Content-Type: application/json

  {
    "id_card":2
  }

###
GET http://localhost:3001/game HTTP/1.1
Content-Type: application/json

{
  "playerOneCard": 1,
  "playerTwoCard": 3
}

